# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
    assignees:
      - "chrisdodd93"
    target-branch: main
    versioning-strategy: lockfile-only
    reviewers:
      - "govuk-one-login/fog"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    # Only allow updates to the lockfile for pip and
    # ignore any version updates that affect the manifest
    versioning-strategy: lockfile-only
    open-pull-requests-limit: 3
    assignees:
      - "chrisdodd93"
    reviewers:
      - "govuk-one-login/fog"
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
    assignees:
      - "chrisdodd93"
    reviewers:
      - "govuk-one-login/fog"

