name: Publish Stack Set to Service Catalog
# On a push to the main branch or via manual execution this workflow will 
# Synth the CloudFormation templates from the typescript cdk run jests tests
# against the resultant files and confirm they contain the expected resources.
# The Synth will run again and if a difference is found they will update the
# Service Catalog Stack Set. 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
      - name: Install node dependencies
        run: npm ci
      - name: Run Jest Tests
        run: npm test

  validate:
    runs-on: ubuntu-latest
    needs: 
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'synth'
          cdk_version: '2.81.0'
          working_dir: 'cdk.out'
      - name: Run Checkov action
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: cdk.out/
          framework: cloudformation
          skip_check: CKV_AWS_107,CKV_AWS_111
